allowBuilds:
  '@biomejs/biome': true
  cn-font-split: true
  esbuild: true
  koffi: true
  protobufjs: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - cn-font-split
  - koffi
  - protobufjs
