name = "firedre"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "firedre-blog"
database_id = "771d3eee-4a4f-4765-a477-8e9022aff4b1"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "firedre-blog"
