import type { Group } from "./types";

export const siteGroups: Group[] = [
	{
		key: "basic",
		title: "基本信息",
		category: "站点配置",
		fields: [
			{ name: "title", label: "站点标题", type: "text" },
			{ name: "subtitle", label: "副标题", type: "text" },
			{ name: "description", label: "站点描述", type: "textarea" },
			{ name: "keywords", label: "关键词（逗号分隔）", type: "textarea" },
			{
				name: "siteUrl",
				label: "站点地址",
				type: "text",
				placeholder: "https://example.com",
			},
			{
				name: "siteStartDate",
				label: "建站日期",
				type: "text",
				placeholder: "2025-01-01",
			},
			{
				name: "timezone",
				label: "时区",
				type: "text",
				placeholder: "Asia/Shanghai",
			},
			{
				name: "hue",
				label: "主题色相 (0-360)",
				type: "number",
				hint: "改变全局主题色",
			},
			{
				name: "defaultMode",
				label: "默认主题模式",
				type: "select",
				options: [
					{ label: "跟随系统", value: "system" },
					{ label: "浅色", value: "light" },
					{ label: "深色", value: "dark" },
				],
			},
			{
				name: "pageWidth",
				label: "页面宽度 (%)",
				type: "number",
				hint: "默认 100",
			},
			{ name: "categoryBar", label: "显示分类栏", type: "boolean" },
			{
				name: "categoryStyle",
				label: "分类样式",
				type: "select",
				options: [
					{ label: "矩形", value: "rectangle" },
					{ label: "胶囊", value: "pill" },
				],
			},
			{
				name: "tagStyle",
				label: "标签样式",
				type: "select",
				options: [
					{ label: "胶囊", value: "pill" },
					{ label: "灰色胶囊", value: "pill-gray" },
					{ label: "矩形", value: "rectangle" },
				],
			},
			{ name: "pageFriends", label: "页面开关：友链", type: "boolean" },
			{ name: "pageGuestbook", label: "页面开关：留言板", type: "boolean" },
			{ name: "pageDynamic", label: "页面开关：动态", type: "boolean" },
			{ name: "pageGallery", label: "页面开关：相册", type: "boolean" },
			{ name: "pageBooknav", label: "页面开关：书签导航", type: "boolean" },
			{ name: "pageBilibili", label: "页面开关：哔哩哔哩", type: "boolean" },
			{ name: "pageBangumi", label: "页面开关：番组计划", type: "boolean" },
			{ name: "pageVndb", label: "页面开关：VNDB", type: "boolean" },
			{ name: "pageMal", label: "页面开关：MyAnimeList", type: "boolean" },
			{ name: "pageSponsor", label: "页面开关：打赏", type: "boolean" },
			{ name: "cardBorder", label: "卡片边框", type: "boolean" },
			{ name: "cardFollowTheme", label: "卡片跟随主题", type: "boolean" },
			{
				name: "cardRadius",
				label: "卡片圆角 (rem)",
				type: "number",
				hint: "前台所有卡片的圆角半径，默认 1（如 0 为直角、2 为更大圆角）",
			},
			{ name: "faviconUrl", label: "网站图标 URL", type: "text" },
		],
	},
	{
		key: "panel",
		title: "显示设置面板",
		category: "站点配置",
		fields: [
			{ name: "enable", label: "启用设置面板", type: "boolean" },
			{ name: "themeColorSwitchable", label: "主题色可调", type: "boolean" },
			{ name: "layoutSwitchable", label: "布局可调", type: "boolean" },
			{ name: "cardBorderSwitchable", label: "卡片边框可调", type: "boolean" },
			{
				name: "cardFollowThemeSwitchable",
				label: "卡片跟随主题可调",
				type: "boolean",
			},
			{
				name: "wallpaperModeSwitchable",
				label: "壁纸模式可调",
				type: "boolean",
			},
			{ name: "wavesSwitchable", label: "波浪特效可调", type: "boolean" },
			{ name: "gradientSwitchable", label: "渐变背景可调", type: "boolean" },
			{ name: "bannerTitleSwitchable", label: "横幅标题可调", type: "boolean" },
			{
				name: "bannerCarouselSwitchable",
				label: "横幅轮播可调",
				type: "boolean",
			},
			{ name: "sakuraSwitchable", label: "樱花可调", type: "boolean" },
			{
				name: "overlayOpacitySwitchable",
				label: "壁纸透明度可调",
				type: "boolean",
			},
			{
				name: "overlayBlurSwitchable",
				label: "背景模糊度可调",
				type: "boolean",
			},
			{
				name: "overlayCardOpacitySwitchable",
				label: "卡片透明度可调",
				type: "boolean",
			},
		],
	},
	{
		key: "effects",
		title: "特效设置",
		category: "站点配置",
		fields: [
			{ name: "sakura", label: "樱花飘落", type: "boolean" },
			{ name: "sakuraNum", label: "樱花数量", type: "number", hint: "默认 21" },
			{ name: "waves", label: "波浪特效", type: "boolean" },
			{ name: "gradient", label: "渐变背景", type: "boolean" },
			{ name: "bannerCarousel", label: "横幅轮播效果", type: "boolean" },
			{
				name: "limitTimes",
				label: "樱花越界限制次数",
				type: "number",
				placeholder: "-1 无限",
			},
		],
	},
	{
		key: "profile",
		title: "个人资料",
		category: "站点配置",
		fields: [
			{ name: "name", label: "昵称 / 作者", type: "text" },
			{ name: "avatar", label: "头像 URL", type: "text" },
			{ name: "bio", label: "个人简介", type: "textarea" },
			{ name: "location", label: "所在地", type: "text" },
			{ name: "email", label: "邮箱", type: "text" },
			{
				name: "links",
				label: "社交链接",
				type: "records",
				hidden: true,
				recordFields: [
					{ key: "name", label: "名称", required: true },
					{ key: "url", label: "链接", required: true },
					{ key: "icon", label: "图标" },
					{
						key: "showName",
						label: "显示名称(true/false)",
						valueType: "boolean",
					},
				],
				placeholder:
					"每行一个，字段顺序：名称 | 链接 | 图标 | 显示名称(true/false)\n如：GitHub | https://github.com/x | fa7-brands:github | true",
			},
		],
	},
	{
		key: "theme",
		title: "背景壁纸",
		category: "站点配置",
		fields: [
			{
				name: "mode",
				label: "壁纸模式",
				type: "select",
				options: [
					{ label: "横幅", value: "banner" },
					{ label: "全屏", value: "fullscreen" },
					{ label: "叠加", value: "overlay" },
					{ label: "无", value: "none" },
				],
			},
			{ name: "playerUrl", label: "背景视频播放地址 (mp4)", type: "text" },
			{
				name: "playerEnable",
				label: "背景视频播放按钮（播放按钮视频开关）",
				type: "boolean",
				hint: "配置视频后导航栏显示播放按钮",
			},
			{
				name: "bannerUrl",
				label: "桌面壁纸图片 URL（多张用逗号分隔）",
				type: "text",
			},
			{
				name: "mobileImages",
				label: "移动壁纸图片 URL（多张用逗号分隔）",
				type: "text",
			},
			{
				name: "dimOpacity",
				label: "壁纸遮罩透明度 (0-1)",
				type: "number",
				hint: "横幅与透明全屏模式共用：值越大壁纸越暗淡",
			},
			{
				name: "playerMode",
				label: "多视频播放模式",
				type: "select",
				options: [
					{ label: "顺序", value: "order" },
					{ label: "随机", value: "random" },
				],
			},
			{ name: "homeTextEnable", label: "主页横幅文字", type: "boolean" },
			{ name: "homeTitle", label: "主页横幅主标题", type: "text" },
			{
				name: "homeTitleSize",
				label: "主标题字号",
				type: "text",
				placeholder: "4.5rem",
			},
			{
				name: "homeSubtitles",
				label: "主页副标题",
				type: "records",
				recordFields: [{ key: "", label: "副标题" }],
				placeholder: "每行一条，如：In Reddened Chrysalis, I Once Rest",
			},
			{
				name: "homeSubtitleSize",
				label: "副标题字号",
				type: "text",
				placeholder: "1.5rem",
			},
			{
				name: "typewriter",
				label: "打字机效果",
				type: "boolean",
				hint: "开启=循环显示副标题；关闭=随机一条",
			},
			{
				name: "typewriterSpeed",
				label: "打字速度 (ms)",
				type: "number",
				hint: "默认 100",
			},
			{
				name: "typewriterDeleteSpeed",
				label: "删除速度 (ms)",
				type: "number",
				hint: "默认 50",
			},
			{
				name: "typewriterPauseTime",
				label: "暂停时间 (ms)",
				type: "number",
				hint: "默认 2000",
			},
			{ name: "carousel", label: "横幅轮播", type: "boolean" },
			{
				name: "carouselInterval",
				label: "轮播间隔 (ms)",
				type: "number",
				hint: "默认 5000",
			},
			{
				name: "carouselTransition",
				label: "轮播过渡效果",
				type: "select",
				options: [
					{ label: "缩放", value: "zoom" },
					{ label: "淡入淡出", value: "fade" },
					{ label: "滑动", value: "slide" },
					{ label: "缓慢缩放", value: "kenburns" },
				],
			},
			{
				name: "overlayOpacity",
				label: "壁纸透明度 (0-1，仅叠加模式)",
				type: "number",
				hint: "仅叠加模式生效；横幅/透明全屏请用「壁纸遮罩透明度」",
			},
			{ name: "overlayBlur", label: "背景模糊度 (px)", type: "number" },
			{
				name: "overlayCardOpacity",
				label: "卡片透明度 (0-1)",
				type: "number",
				hint: "卡片背景透明度，值越小越透明",
			},
		],
	},
	{
		key: "sidebar",
		title: "侧边栏",
		category: "站点配置",
		fields: [
			{ name: "showProfile", label: "个人资料卡片", type: "boolean" },
			{ name: "showAnnouncement", label: "公告卡片", type: "boolean" },
			{ name: "showMusic", label: "音乐播放器卡片", type: "boolean" },
			{ name: "showCategories", label: "分类卡片", type: "boolean" },
			{ name: "showTags", label: "标签卡片", type: "boolean" },
			{ name: "showCalendar", label: "日历卡片", type: "boolean" },
			{
				name: "hideSidebarOnPostPage",
				label: "文章页隐藏侧边栏",
				type: "boolean",
			},
			{
				name: "noSidebarContentWidth",
				label: "无侧栏时内容栏宽度比例",
				type: "number",
				hint: "0-1，例如 0.6 表示内容栏占「侧栏+内容栏」总宽的 60%；不设置或 >=1 则铺满",
			},
		],
	},
	{
		key: "nav",
		title: "导航栏",
		category: "站点配置",
		fields: [
			{
				name: "navbarMode",
				label: "导航栏模式",
				type: "select",
				options: [
					{ label: "静态（随页面滚动消失）", value: "static" },
					{ label: "固定（常显）", value: "fixed" },
					{ label: "动态（下滑隐藏、上滑显示）", value: "dynamic" },
				],
				hint: "默认固定；动态模式在壁纸区域保持可见，进入内容区后下滑隐藏",
			},
		],
	},
	{
		key: "post",
		title: "文章页底部区块",
		category: "站点配置",
		fields: [
			{ name: "share", label: "分享卡片", type: "boolean" },
			{ name: "postNavigation", label: "上一篇/下一篇导航", type: "boolean" },
			{ name: "relatedPosts", label: "相关文章推荐", type: "boolean" },
			{ name: "randomPosts", label: "随机文章推荐", type: "boolean" },
		],
	},
];
