// auto-generated by album-webdav-config plugin
import type { AlbumWebDavFrontmatterConfig } from "../types/album";

export const albumWebDavPublicConfig: Record<
	string,
	AlbumWebDavFrontmatterConfig
> = {};

export function getAlbumWebDavPublicConfig(slug: string) {
	return albumWebDavPublicConfig[slug];
}
