import { resolveSiteLang } from "../../utils/site-config-utils";

// settingsDefaults 的 site 域分组（自 settings-defaults.ts 机械拆分，内容零改动）
export const siteDefaults = {
	basic: {
		cardBorder: false,
		cardFollowTheme: false,
		cardRadius: 1,
		faviconUrl: "/favicon/firefly-32.png",
		title: "Firedre",
		subtitle: "Demo site",
		description:
			"Firedre 是基于 Astro Firefly 主题深度云原生化改造的个人博客，全站运行于 Cloudflare Pages / D1 / R2：文章、动态、相册、书签导航、追番数据与留言板一应俱全，后台可视化管理，无需服务器即可稳定运行。",
		siteUrl: "https://firedre.994613.xyz",
		siteStartDate: "2025-01-01",
		timezone: "Asia/Shanghai",
		pageWidth: 100,
		categoryBar: true,
		categoryStyle: "rectangle",
		tagStyle: "pill",
		hue: 165,
		defaultMode: "system",
		pageFriends: true,
		pageGuestbook: true,
		pageDynamic: true,
		pageGallery: true,
		pageBooknav: true,
		pageBilibili: true,
		pageBangumi: false,
		pageVndb: false,
		pageMal: true,
		pageSponsor: true,
		keywords:
			"Firedre,Astro,Cloudflare,个人博客,技术博客,云原生,D1,R2,ACGN,动态,相册,书签导航,追番",
		// ── 结构字段（A4：自 siteConfig 原值搬移，非后台可编辑项） ──
		lang: resolveSiteLang("zh_CN"),
		foldArticle: true,
		pagination: { postsPerPage: 10 },
		favicon: [{ src: "/favicon/firefly-32.png" }],
		navbar: {
			logo: {
				type: "image",
				value: "assets/images/logo/firefly-light.png",
				valueDark: "assets/images/logo/firefly-dark.png",
				alt: "🍀",
			},
			title: "Firefly",
			widthFull: false,
			menuAlign: "center",
			followTheme: false,
			navbarMode: "fixed",
		},
		imageOptimization: {
			formats: "webp",
			quality: 85,
			noReferrerDomains: [
				"*.hdslb.com",
				"*.bilibili.com",
				"*.myanimelist.net",
				"*.vndb.org",
			],
		},
		postListLayout: {
			defaultMode: "list",
			mobileDefaultMode: "grid",
			coverPosition: "right",
			descriptionLines: 2,
			showStatsIcons: true,
			tagsPosition: "bottom",
			tagsBottomStyle: "chip",
			meta: {
				showPublished: true,
				showCategory: true,
				showTags: true,
				tagCount: 3,
				showWords: false,
				showReadingTime: false,
			},
			stats: {
				showPublished: true,
				showWords: true,
				showReadingTime: true,
			},
			grid: { masonry: false, columnWidth: 320, coverFullWidth: false },
		},
		bilibili: { uid: "38932988" },
		bangumi: {
			userId: "1143164",
			mode: "dynamic",
			apiUrl: "https://api.bangumi.pro",
			subjectBaseUrl: "https://api.bangumi.pro/subject/",
			categoryOrder: ["anime", "book", "music", "game"],
			nsfw: "hide",
		},
		vndb: {
			userId: "u358128",
			mode: "static",
			downloadCovers: false,
			apiUrl: "https://api.vndb.org/kana",
			vnBaseUrl: "https://vndb.org/",
			apiToken: "",
			nsfw: "hide",
		},
		mal: {
			username: "",
			clientId: "",
			apiUrl: "https://api.myanimelist.net/v2",
			animeBaseUrl: "https://myanimelist.net/anime/",
			mangaBaseUrl: "https://myanimelist.net/manga/",
			nsfw: "hide",
		},
	},
	profile: {
		location: "",
		email: "",
		name: "Firedre",
		avatar: "/favicon/firefly-192.png",
		bio: "Hello, I'm Firedre.",
		links:
			'[{"name":"qq","icon":"fa7-brands:qq","url":"https://qm.qq.com/q/ZGsFa8qX2G","showName":false},{"name":"GitHub","icon":"fa7-brands:github","url":"https://github.com/jeio258","showName":false},{"name":"Email","icon":"fa7-solid:envelope","url":"mailto:xiaye@msn.com","showName":false},{"name":"RSS","icon":"fa7-solid:rss","url":"/rss/","showName":false}]',
	},
	panel: {
		enable: false,
		overlaySwitchable: false,
		themeColorSwitchable: false,
		layoutSwitchable: false,
		cardBorderSwitchable: false,
		cardFollowThemeSwitchable: false,
		wallpaperModeSwitchable: false,
		wavesSwitchable: false,
		gradientSwitchable: false,
		bannerTitleSwitchable: false,
		bannerCarouselSwitchable: false,
		sakuraSwitchable: false,
		overlayOpacitySwitchable: false,
		overlayBlurSwitchable: false,
		overlayCardOpacitySwitchable: false,
	},
	announcement: {
		enabled: true,
		sections: "",
		title: "",
		content: "",
	},
} as const;
