// 后台/运行时默认设置（手工维护）。前端后台表单默认值见 settings-defaults.json。
export const settingsDefaults = {
	basic: {
		title: "Firefly",
		subtitle: "Demo site",
		description:
			"Firefly 是一款基于 Astro 框架和 Fuwari 模板开发的清新美观且现代化个人博客主题模板，专为技术爱好者和内容创作者设计。该主题融合了现代 Web 技术栈，提供了丰富的功能模块和高度可定制的界面，让您能够轻松打造出专业且美观的个人博客网站。",
		siteUrl: "https://firedre.994613.xyz",
		siteStartDate: "2025-01-01",
		timezone: "Asia/Shanghai",
		pageWidth: 100,
		categoryBar: true,
		categoryStyle: "rectangle",
		tagStyle: "pill",
		hue: 165,
		defaultMode: "system",
		pageFriends: true,
		pageGuestbook: true,
		pageDynamic: true,
		pageGallery: true,
		pageBooknav: true,
		pageBilibili: false,
		pageBangumi: false,
		pageVndb: false,
		pageMal: false,
		pageSponsor: true,
		keywords: "Firefly,Fuwari,Astro,ACGN,博客,技术博客,静态博客",
	},
	panel: {
		enable: false,
		themeColorSwitchable: false,
		layoutSwitchable: false,
		cardBorderSwitchable: false,
		cardFollowThemeSwitchable: false,
		wallpaperModeSwitchable: false,
		wavesSwitchable: false,
		gradientSwitchable: false,
		bannerTitleSwitchable: false,
		bannerCarouselSwitchable: false,
		sakuraSwitchable: false,
	},
	profile: {
		name: "Firefly",
		avatar: "assets/images/avatar.avif",
		bio: "Hello, I'm Firefly.",
		links:
			'[{"name":"qq","icon":"fa7-brands:qq","url":"https://qm.qq.com/q/ZGsFa8qX2G","showName":false},{"name":"GitHub","icon":"fa7-brands:github","url":"https://github.com/CuteLeaf","showName":false},{"name":"Email","icon":"fa7-solid:envelope","url":"mailto:xiaye@msn.com","showName":false},{"name":"RSS","icon":"fa7-solid:rss","url":"/rss/","showName":false}]',
	},
	theme: {
		mode: "banner",
		playerEnable: true,
		bannerUrl:
			"assets/images/DesktopWallpaper/d1.avif,assets/images/DesktopWallpaper/d2.avif,assets/images/DesktopWallpaper/d3.avif,assets/images/DesktopWallpaper/d4.avif,assets/images/DesktopWallpaper/d5.avif,assets/images/DesktopWallpaper/d6.avif",
		mobileImages:
			"assets/images/MobileWallpaper/m1.avif,assets/images/MobileWallpaper/m2.avif,assets/images/MobileWallpaper/m3.avif,assets/images/MobileWallpaper/m4.avif,assets/images/MobileWallpaper/m5.avif,assets/images/MobileWallpaper/m6.avif",
		playerUrl: "https://bed.twoleaf.cn/file/1785658612716_firefly.mp4",
		dimOpacity: 0.2,
		playerMode: "random",
		homeTextEnable: true,
		homeTitle: "Lovely firefly!",
		homeTitleSize: "4.5rem",
		homeSubtitles:
			'["In Reddened Chrysalis, I Once Rest","From Shattered Sky, I Free Fall","Amidst Silenced Stars, I Deep Sleep","Upon Lighted Fyrefly, I Soon Gaze","From Undreamt Night, I Thence Shine","In Finalized Morrow, I Full Bloom"]',
		homeSubtitleSize: "1.5rem",
		typewriter: true,
		typewriterSpeed: 100,
		typewriterDeleteSpeed: 50,
		typewriterPauseTime: 2000,
		carousel: false,
		carouselInterval: 5000,
		carouselTransition: "zoom",
		overlayOpacity: 0.8,
		overlayBlur: 10,
		overlayCardOpacity: 0.6,
	},
	nav: {
		navItems:
			'[{"name":"主页","url":"/","icon":"material-symbols:home"},{"name":"文章","url":"#","icon":"material-symbols:article","children":[{"name":"归档","url":"/archive/","icon":"material-symbols:archive"},{"name":"分类","url":"/categories/","icon":"material-symbols:folder-open-rounded"},{"name":"标签","url":"/tags/","icon":"material-symbols:tag-rounded"},{"name":"系列","url":"/series/","icon":"material-symbols:layers"}]},{"name":"社交","url":"#","icon":"material-symbols:group","children":[{"name":"友链","url":"/friends/","icon":"material-symbols:link-2-rounded","pageKey":"friends"},{"name":"留言","url":"/guestbook/","icon":"material-symbols:chat","pageKey":"guestbook"}]},{"name":"我的","url":"#","icon":"material-symbols:person","children":[{"name":"动态","url":"/dynamic/","icon":"material-symbols:forum-rounded","pageKey":"dynamic"},{"name":"相册","url":"/gallery/","icon":"material-symbols:photo-library","pageKey":"gallery"},{"name":"书签导航","url":"/booknav/","icon":"material-symbols:bookmarks","pageKey":"booknav"},{"name":"哔哩哔哩","url":"/bilibili/","icon":"fa7-brands:bilibili","pageKey":"bilibili"},{"name":"番组计划","url":"/bangumi/","icon":"material-symbols:movie","pageKey":"bangumi"},{"name":"VNDB","url":"/vndb/","icon":"material-symbols:chrome-reader-mode-rounded","pageKey":"vndb"},{"name":"AnimeList","url":"/myanimelist/","icon":"material-symbols:menu-book","pageKey":"mal"}]},{"name":"关于","url":"#","icon":"material-symbols:info","children":[{"name":"打赏","url":"/sponsor/","icon":"material-symbols:favorite","pageKey":"sponsor"},{"name":"关于我","url":"/about/","icon":"material-symbols:person"}]},{"name":"链接","url":"#","icon":"material-symbols:link","children":[{"name":"GitHub","url":"https://github.com/CuteLeaf/Firefly","external":true,"icon":"fa7-brands:github"},{"name":"Gitee","url":"https://gitee.com/CuteLeaf/Firefly","external":true,"icon":"fa7-brands:gitee"},{"name":"QQ交流群","url":"https://qm.qq.com/q/ZGsFa8qX2G","external":true,"icon":"fa7-brands:qq"},{"name":"Firefly文档","url":"https://docs-firefly.cuteleaf.cn","external":true,"icon":"material-symbols:docs"}]}]',
	},
	sidebar: {
		hideSidebarOnPostPage: false,
		showBothSidebarsOnPostPage: true,
	},
	font: {
		enable: true,
		codeFont: "",
		bannerTitleFont: "",
		bannerSubtitleFont: "",
		navbarTitleFont: "",
	},
	comment: {
		type: "none",
		giscusRepo: "CuteLeaf/Firefly",
		giscusRepoId: "R_kgD2gfdFGd",
		giscusCategory: "General",
		giscusCategoryId: "DIC_kwDOKy9HOc4CegmW",
		twikooEnvId: "https://twikoo.vercel.app",
		twikooJsUrl:
			"https://cdn.jsdelivr.net/npm/twikoo@1.7.14/dist/twikoo.min.js",
		walineServer: "https://waline.vercel.app",
		disqusShortname: "firefly",
		artalkServer: "https://artalk.example.com/",
	},
	cover: {
		showLoading: false,
	},
	music: {
		showInNavbar: true,
		showInSidebar: true,
		mode: "local",
		volume: 0.7,
		playMode: "list",
		showLyrics: false,
		metingApi:
			"https://api.i-meto.com/meting/api?server=:server&type=:type&id=:id&r=:r",
		metingServer: "netease",
		metingType: "playlist",
		metingId: "10046455237",
		metingAuth: "",
		metingFallbackApis:
			'["https://api.injahow.cn/meting/?server=:server&type=:type&id=:id","https://api.moeyao.cn/meting/?server=:server&type=:type&id=:id"]',
		localPlaylist:
			'[{"name":"使一颗心免于哀伤","artist":"知更鸟 / HOYO-MiX / Chevy","url":"/assets/music/使一颗心免于哀伤-哼唱.mp3","cover":"/assets/music/cover/109951169585655912.webp","lrc":""}]',
	},
	mermaid: {
		enabled: true,
	},
	dynamic: {
		enabled: true,
		title: "",
		description: "",
		profileUrl: "/about/",
		showComment: true,
		itemsPerPage: 20,
		apiUrl: "/api/dynamic.json",
	},
	friends: {
		enabled: true,
	},
	gallery: {
		enabled: true,
	},
	bookmarks: {
		title: "",
		description: "",
	},
	sponsor: {
		title: "",
		description: "",
		showButtonInPost: true,
		showSponsorsList: true,
	},
	effects: {
		sakura: false,
		sakuraNum: 21,
		limitTimes: -1,
		waves: true,
		gradient: true,
		bannerCarousel: false,
	},
	announcement: {
		title: "",
		content: "",
	},
	footer: {
		enable: false,
	},
	license: {
		enabled: true,
		name: "CC BY-NC-SA 4.0",
		url: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
		icon: "",
	},
	pio: {
		enabled: false,
		type: "live2d",
		position: "bottom-left",
		size: {
			width: 200,
			height: 200,
		},
	},
	analytics: {},
} as const;
